server {
	listen       443 ssl;  # Listen on port 443.
	server_name  melfersi.42.fr;  # Server name (can be a domain name or IP address)

	# SSL configuration.
	ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
	ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;

	ssl_protocols TLSv1.2 TLSv1.3;

	root   /var/www/html;  # Root directory for serving files.
	index  index.html index.php;  # Default index files.
	# Location block for handling requests to the root URL.
	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

}