services:
  nginx:
    build: ./requirements/nginx
    image: my_nginx1
    container_name: my_nginx
    ports:
      - "443:443"
    volumes: 
      - wordpressVOL:/var/www/html
    networks:
      - my_network
    depends_on:
      - WordPress
    env_file:
      - .env
    restart: always
  WordPress:
    build: ./requirements/wordpress
    image: wordpress-php-fpm
    container_name: my_php-fpm-wordpress
    volumes:
      - wordpressVOL:/var/www/html
    networks:
      - my_network
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    restart: always
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: my_mariadb
    volumes:
      - mariadbVOL:/var/lib/mysql
    networks:
      - my_network
    env_file:
      - .env
    restart: always
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: my_redis
    networks:
      - my_network
    env_file:
      - .env
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: my_ftp
    networks:
      - my_network
    ports:
      - 20-21:20-21
      - 60000-60010:60000-60010
    env_file:
      - .env
    volumes:
      - wordpressVOL:/var/www/html
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: my_adminer
    networks:
      - my_network
    ports:
      - 8080:8080
    restart: always
  portainer:
    build: ./requirements/bonus/portainer
    image: portainer
    container_name: my_portainer
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    restart: always
  staticwp:
    build: ./requirements/bonus/staticWebPage
    image: staticwp
    container_name: my_staticWebPage
    ports:
      - 80:80
    restart: always

volumes:
  wordpressVOL:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpressVOL
  mariadbVOL:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadbVOL
networks:
  my_network:
  