server {
	listen       80; 
	server_name  static;

	root   /var/www/html;  # Root directory for serving files.
	index  index.html;  # Default index files.
	# Location block for handling requests to the root URL.
	location / {
		try_files $uri $uri/ =404;
	}
}