# Set The Server To Run In Standalone Mode
background=NO

# Disable Anonymous Login
anonymous_enable=NO

# Allow Local Users To Login
local_enable=YES

# Allow Users To Write (Delete, Modify, Upload)
write_enable=YES

# Ensure The Users Cannot Go Back
chroot_local_user=YES

# Set Root Path
local_root=/var/www/html

# Listen To IPV4
listen=YES

# Set The Port
# listen_port=21


# Use Passive Mode
pasv_enable=YES
pasv_min_port=50011
pasv_max_port=51000
